"""ticket payload + locked_value

Revision ID: 692f664d5bd5
Revises: c929a949d2e6
Create Date: 2026-06-01 09:19:58.625205
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '692f664d5bd5'
down_revision: str | None = 'c929a949d2e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'need_fact_tickets',
        sa.Column('payload', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    op.add_column('need_fact_tickets', sa.Column('locked_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('need_fact_tickets', 'locked_value')
    op.drop_column('need_fact_tickets', 'payload')
    # ### end Alembic commands ###
