"""theme research_report

Revision ID: afd606d42750
Revises: 692f664d5bd5
Create Date: 2026-06-02 07:56:30.626153
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'afd606d42750'
down_revision: str | None = '692f664d5bd5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('research_report', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'research_report')
    # ### end Alembic commands ###
